language: node_js

sudo: required
services:
  - docker

before_install:
  - docker build -t nishik/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nishik/multi-docker npm run test -- --coverage

after_success:
  - docker build -t nishik/multi-client ./client
  - docker build -t nishik/multi-nginx ./nginx
  - docker build -t nishik/multi-api ./api
  - docker build -t nishik/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin # DOCKER_ID and DOCKER_PASSWORD should be set up in Travis env varibles
  #Take those images and push them to docker hub
  - docker push nishik/multi-client
  - docker push nishik/multi-nginx
  - docker push nishik/multi-api
  - docker push nishik/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "multi-docker"
#   env: "MultiDocker-env"
#   bucket_name: "elasticbeanstalk-us-east-2-780374467171"
#   bucket_path: "multi-docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"